sudo: required
dist: trusty

language: node_js
node_js:
  - 5.6

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod ugo+x deploy.sh

install:
  - npm install -g firebase-tools

after_success:
  - gulp build
  - ls -al
  - ./deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change

